# Nginx server blok pre staticky React frontend.
server {
    # Kontajner pocuva na porte 80.
    listen 80;
    # Lokalny nazov servera pre jednoduche kontajnerove nasadenie.
    server_name localhost;

    # Tu su nakopirovane subory z React buildu.
    root /usr/share/nginx/html;
    # index.html je vstupny bod single-page aplikacie.
    index index.html;

    # Fallback pre React routing pri refreshi podstranok.
    location / {
        # Ak subor neexistuje, vrati sa index.html a routing riesi frontend.
        try_files $uri /index.html;
    }
}
